name: Auto Update README

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *" # 매일 자정 실행

jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt
        else
          echo "requirements.txt not found, installing default dependencies"
          pip install requests pandas  # 필요한 패키지 예시

    - name: Run update.py script
      run: |
        python update.py  # update.py 파일 실행

    - name: Check if README.md changed
      run: |
        git diff --exit-code
      continue-on-error: true  # 변경 사항이 없어도 워크플로우가 실패하지 않도록 설정

    - name: Commit changes
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add -A
        git commit -m "auto update README.md" || echo "No changes to commit"

    - name: Push changes
      run: |
        git push || echo "No changes to push"
