name: Auto Update README

on:
  schedule:
    - cron: '0 0 * * *' # 매일 자정 실행

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found. Skipping dependencies."
      
      - name: Run update.py
        run: python update.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github nickname"
          git config --global user.email "github email"
          git diff
          if ! git diff --quiet; then
            git add README.md
            git commit -m "auto update README.md"
            git push
          else
            echo "No changes to commit."
